name: justcause
channels:
  - r
  - pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _r-mutex
  - _tflow_select
  - absl-py
  - apipkg
  - arrow-cpp
  - asn1crypto
  - astor
  - atomicwrites
  - attrs
  - backcall
  - backports
  - backports.os
  - blas
  - bleach
  - boost-cpp
  - brotli
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - clang
  - clangxx
  - compiler-rt
  - contextlib2
  - coverage
  - coveralls
  - cryptography
  - curl
  - cycler
  - cython
  - decorator
  - defusedxml
  - docopt
  - double-conversion
  - entrypoints
  - execnet
  - flake8
  - fontconfig
  - freetype
  - fribidi
  - gast
  - gettext
  - gflags
  - glib
  - glog
  - graphite2
  - grpc-cpp
  - grpcio
  - gsl
  - h5py
  - harfbuzz
  - hdf5
  - icu
  - idna
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - krb5
  - libcurl
  - libcxx
  - libcxxabi
  - libedit
  - libevent
  - libffi
  - libgfortran
  - libiconv
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libtiff
  - libxml2
  - llvm
  - llvm-openmp
  - lz4-c
  - make
  - markdown
  - markupsafe
    # Required for causaml to work instantly
  - matplotlib==2.2.4
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parquet-cpp
  - parso
  - path.py
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - py
    # Required in order to read the parquet files properly
  - pyarrow>=0.15
  - pycodestyle
  - pycparser
  - pyflakes
  - pygments
  - pymongo
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - pytest
  - pytest-cov
  - pytest-fixture-config
  - pytest-shutil
  - pytest-virtualenv
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - r-assertthat
  - r-base
  - r-bh
  - r-bit
  - r-bit64
  - r-blob
  - r-cli
  - r-crayon
  - r-dbi
  - r-dbplyr
  - r-digest
  - r-dplyr
  - r-fansi
  - r-glue
  - r-magrittr
  - r-memoise
  - r-pillar
  - r-pkgconfig
  - r-plogr
  - r-prettyunits
  - r-purrr
  - r-r6
  - r-rcpp
  - r-rlang
  - r-rsqlite
  - r-tibble
  - r-tidyselect
  - r-utf8
  - re2
  - readline
  - requests
  - rpy2
    # Currently required to downgrade scikit-learn in order for causaml to compile
  - scikit-learn==0.20.3
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - snappy
  - sqlite
  - statsmodels
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - terminado
  - testpath
  - thrift-cpp
  - tk
  - tktable
  - tornado
  - traitlets
  - uriparser
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - wrapt
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - aspy-yaml
    - cfgv
    - colorama
    - gitdb2
    - gitpython
    - identify
    - jsonpickle
    - munch
    - nodeenv
    - causalml
    - pre-commit
    - py-cpuinfo
    - sacred
    - smmap2
    - toml
    - virtualenv
